appimoveis/urls.py
from django.contrib import admin
from django.urls import path
from empreendimentos import views
from empreendimentos.views import reservar_unidade, detalhes_empreendimento, login_view, logout_view, faq


urlpatterns = [
    path('', views.home, name='home'),
    path('faq/', faq, name='faq'),
    path('admin/', admin.site.urls),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('cadastrar_empreendimento/', views.cadastrar_empreendimento, name='cadastrar_empreendimento'),
    path('lista_empreendimentos/', views.lista_empreendimentos, name='lista_empreendimentos'),
    # Cadastro de Unidades
    path('cadastrar_unidade/<int:empreendimento_id>/', views.cadastrar_unidade, name='cadastrar_unidade'),

    # Edição de Unidades
    path('editar_unidade/<int:unidade_id>/', views.editar_unidade, name='editar_unidade'),

    # Exclusão de Unidades
    path('excluir_unidade/<int:unidade_id>/', views.excluir_unidade, name='excluir_unidade'),

    # Listagem de Unidades
    path('listar_unidades/<int:empreendimento_id>/', views.listar_unidades, name='listar_unidades'),

    path('detalhes_empreendimento/<int:empreendimento_id>/reservar_unidade/', reservar_unidade, name='reservar_unidade'),
    path('detalhes_empreendimento/<int:empreendimento_id>/', detalhes_empreendimento, name='detalhes_empreendimento'),




]
    

empreendimentos/models.py
from django.db import models
from django.utils import timezone
from django import forms
from django.contrib.auth import get_user_model


class Empreendimento(models.Model):
    nome = models.CharField(max_length=255)
    descricao = models.TextField()
    material_divulgacao = models.URLField(blank=True, null=True, verbose_name='Link do Material de Divulgação')
    imagem = models.ImageField(upload_to='static/media/empreendimento_imagens/', null=True, blank=True)

    
    TIPOS_EMPREENDIMENTO = (
        ('predio', 'Prédio'),
        ('loteamento', 'Loteamento'),
    )
    
    tipo_empreendimento = models.CharField(
        max_length=20,
        choices=TIPOS_EMPREENDIMENTO,
        default='predio',
    )

    def __str__(self):
        return self.nome

class Unidade(models.Model):
    reservado_por = models.ForeignKey(get_user_model(), null=True, blank=True, on_delete=models.SET_NULL)
    empreendimento = models.ForeignKey(Empreendimento, on_delete=models.CASCADE, related_name='unidades')
    numero = models.CharField(max_length=10)
    descricao = models.TextField(max_length=1000)
    preco = models.CharField(max_length=15)
    status = models.CharField(max_length=20, choices=[
        ('disponivel', 'Disponível'),
        ('reservada', 'Reservado'),
        ('vendida', 'Vendido'),
    ])
    def nome_reservado_por(self):
        return self.reservado_por.username if self.reservado_por else "N/A"
    def __str__(self):
        return f'Unidade {self.numero} - {self.empreendimento.nome}'
    

empreendimentos/forms.py
from django import forms
from .models import Empreendimento
from .models import Unidade

class EmpreendimentoForm(forms.ModelForm):
    class Meta:
        model = Empreendimento
        fields = ['nome', 'descricao', 'tipo_empreendimento']


class UnidadeForm(forms.ModelForm):
    class Meta:
        model = Unidade
        fields = '__all__'


class ReservaUnidadeForm(forms.Form):
    def __init__(self, empreendimento, *args, **kwargs):
        super(ReservaUnidadeForm, self).__init__(*args, **kwargs)
        self.fields['unidade'].queryset = Unidade.objects.filter(empreendimento=empreendimento, status='disponivel')

    unidade = forms.ModelChoiceField(queryset=Unidade.objects.none(), empty_label=None)

empreendimentos/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Empreendimento, Unidade
from .forms import EmpreendimentoForm, UnidadeForm
from django.shortcuts import render
from .forms import ReservaUnidadeForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required



def home(request):
    return render(request, 'home.html')

def faq(request):
    return render(request, 'faq.html')


def cadastrar_empreendimento(request):
    if request.method == 'POST':
        form = EmpreendimentoForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('lista_empreendimentos')  # Redireciona para a página de listagem de empreendimentos
    else:
        form = EmpreendimentoForm()
    
    return render(request, 'cadastro_empreendimento.html', {'form': form})

@login_required
def lista_empreendimentos(request):
    empreendimentos = Empreendimento.objects.all()
    return render(request, 'lista_empreendimentos.html', {'empreendimentos': empreendimentos})

def cadastrar_unidade(request, empreendimento_id):
    empreendimento = get_object_or_404(Empreendimento, pk=empreendimento_id)

    if request.method == 'POST':
        form = UnidadeForm(request.POST)
        if form.is_valid():
            unidade = form.save(commit=False)
            unidade.empreendimento = empreendimento
            unidade.save()
            return redirect('detalhes_empreendimento', empreendimento_id=empreendimento.id)
    else:
        # Passe o objeto de empreendimento como valor inicial para o campo no formulário
        form = UnidadeForm(initial={'empreendimento': empreendimento})

    return render(request, 'cadastrar_unidade.html', {'empreendimento': empreendimento, 'form': form})


# View para editar uma unidade
def editar_unidade(request, unidade_id):
    unidade = get_object_or_404(Unidade, pk=unidade_id)

    if request.method == 'POST':
        form = UnidadeForm(request.POST, instance=unidade)
        if form.is_valid():
            form.save()
            return redirect('detalhes_empreendimento', empreendimento_id=unidade.empreendimento.id)
    else:
        form = UnidadeForm(instance=unidade)

    return render(request, 'editar_unidade.html', {'form': form, 'unidade': unidade})

# View para excluir uma unidade
def excluir_unidade(request, unidade_id):
    unidade = get_object_or_404(Unidade, pk=unidade_id)
    empreendimento_id = unidade.empreendimento.id

    if request.method == 'POST':
        unidade.delete()
        return redirect('detalhes_empreendimento', empreendimento_id=empreendimento_id)

    return render(request, 'excluir_unidade.html', {'unidade': unidade})

# View para listar todas as unidades de um empreendimento
@login_required
def listar_unidades(request, empreendimento_id):
    empreendimento = get_object_or_404(Empreendimento, pk=empreendimento_id)
    unidades = Unidade.objects.filter(empreendimento=empreendimento)
    
    return render(request, 'listar_unidades.html', {'empreendimento': empreendimento, 'unidades': unidades})

@login_required
def detalhes_empreendimento(request, empreendimento_id):

    #if request.method=='GET':
        empreendimento = get_object_or_404(Empreendimento, pk=empreendimento_id)
        unidades = Unidade.objects.filter(empreendimento=empreendimento)

        return render(request, 'detalhes_empreendimento.html', {'empreendimento': empreendimento, 'unidades': unidades})

@login_required
def reservar_unidade(request, empreendimento_id):
    empreendimento = get_object_or_404(Empreendimento, pk=empreendimento_id)
    unidades_disponiveis = Unidade.objects.filter(empreendimento=empreendimento, status='disponivel')

    if request.method == 'POST':
        form = ReservaUnidadeForm(empreendimento, request.POST)
        if form.is_valid():
            unidade_reservada = form.cleaned_data['unidade']
            # Certifique-se de que o usuário atual esteja associado à reserva
            unidade_reservada.reservado_por = request.user
            unidade_reservada.status = 'reservada'
            unidade_reservada.save()
            return redirect('detalhes_empreendimento', empreendimento_id=empreendimento.id)
    else:
        form = ReservaUnidadeForm(empreendimento)

    return render(request, 'detalhes_empreendimento.html', {'empreendimento': empreendimento, 'unidades': unidades_disponiveis, 'form': form})


def login_view(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            return redirect('lista_empreendimentos')
        else:
            # Lógica para lidar com tentativas de login inválidas
            pass

    return render(request, 'login.html')

def logout_view(request):
    logout(request)
    return redirect('/')

empreendimentos/templates/detalhes_empreendimento copy.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <title>Detalhes do Empreendimento</title>
</head>
<body>
    <h1>Detalhes do Empreendimento</h1>
    <h2>{{ empreendimento.nome }}</h2>
    <p>Descrição: {{ empreendimento.descricao }}</p>
    <p>Tipo de Empreendimento: {{ empreendimento.get_tipo_empreendimento_display }}</p>

    <h2>Unidades</h2>
    <ul>
        {% for unidade in unidades %}
            <li>
                Unidade {{ unidade.numero }} - Status: {{ unidade.status }}
                {% if unidade.status == 'Disponível' %}
                    <button onclick="openModal('{{ unidade.id }}')">Reservar Unidade</button>
                {% endif %}
            </li>
        {% endfor %}
    </ul>

    <!-- Modal de Reserva -->
    <div id="myModal" class="modal">
        <div class="modal-content">
            <span class="close" onclick="closeModal()">&times;</span>
            <h2>Reserva de Unidade</h2>
            <form id="reservaForm">
                {% csrf_token %}
                <input type="hidden" name="unidade_id" id="unidade_id" value="">
                <input type="text" name="nome_cliente" id="nome_cliente" placeholder="Nome do Cliente">
                <button type="button" onclick="submitReserva()">Reservar Unidade</button>
            </form>
        </div>
    </div>

    <script>
        function openModal(unidadeId) {
            document.getElementById('unidade_id').value = unidadeId;
            document.getElementById('myModal').style.display = 'block';
        }

        function closeModal() {
            document.getElementById('myModal').style.display = 'none';
        }

        function submitReserva() {
            const unidadeId = document.getElementById('unidade_id').value;
            const nomeCliente = document.getElementById('nome_cliente').value;

            fetch("{% url 'reservar_unidade' %}", {
                method: "POST",
                headers: {
                    "Content-Type": "application/x-www-form-urlencoded",
                    "X-CSRFToken": "{{ csrf_token }}"
                },
                body: `unidade_id=${unidadeId}&nome_cliente=${nomeCliente}`
            })
            .then(response => response.json())
            .then(data => {
                if (data.success) {
                    alert(data.message);
                    closeModal();
                    location.reload();  // Atualizar a página após a reserva bem-sucedida
                } else {
                    alert(data.message);
                }
            });
        }
    </script>
</body>
</html>

empreendimentos/templates/detalhes_empreendimento.html
{% load static %}

<!DOCTYPE html>
<html lang="pt-br">
<head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <meta charset="UTF-8">
    <title>{{ empreendimento.nome }}</title>
    <script src="{% static 'js/jquery/code.jquery.com_jquery-3.7.1.js' %}"></script>
    <script src="{% static "js/meuscript.js" %}"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <style>
        
        
        .popup {
            display: none;
            position: fixed;
            top: 50%;
            left: 50%;
            transform: translate(-50%, -50%);
            padding: 20px;
            background-color: #fff;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.5);
        }
        body {
            padding: 0px;
        }

    </style>
    

</head>
<body>
 <div class="container">

 
    <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm">
        <img class="my-0 mr-md-auto font-weight-normal" src="/static/media/logopreta.png" width="150px">
        <nav class="my-2 my-md-0 mr-md-3">
          <a class="p-2 text-dark" href="/lista_empreendimentos">Empreendimentos</a>
          <a class="p-2 text-dark" href="/faq/">FAQ</a>
          <a class="p-2 text-dark" href="https://api.whatsapp.com/send/?phone=55048988150135&text&type=phone_number&app_absent=0">Suporte</a>
        </nav>
        {% if user.is_authenticated %}
            <a class="btn btn-outline-primary" href="{% url 'logout' %}">Logout</a>
        {% endif %}

    </div>
    <br>
        <h1>{{ empreendimento.nome }}</h1>
        <p class="lead">{{ empreendimento.descricao }}</p>
        <a class="btn btn-lg btn-primary" href="{{ empreendimento.material_divulgacao }}" role="button">Baixar Materiais de Divulgação &raquo;</a>
    <br>
    <br>
    <br>
    
    <div class="my-class" role="region" tabindex="0">
    <h2>Unidades</h2>
    
    <table class="table table-hover">        
        <thead>
            <tr>
                <th scope="col">Número da Unidade</th>
                <th scope="col">Descrição</th>
                <th scope="col">Preço</th>
                <th scope="col">Status</th>
            </tr>
        </thead>
        <tbody>
            {% for unidade in unidades %}
                <tr>
                    <td scope="row">{{ unidade.numero }}</td>
                    <td><button class="btn btn-primary ver-detalhes-btn" data-toggle="modal" data-target="#descricaoModal{{ unidade.id }}">
                        Ver Detalhes
                    </button></td>
                    <td>{{ unidade.preco }}</td>
                    <td>
                        {% if unidade.status == 'disponivel' %}
                            <button class="btn btn-success">{{ unidade.status }}</button>
                        {% elif unidade.status == 'reservada' %}
                            <button class="btn btn-warning">{{ unidade.status }}</button>
                        {% elif unidade.status == 'vendida' %}
                            <button class="btn btn-secondary">{{ unidade.status }}</button>
                        {% endif %}
                    </td>
                </tr>
                <div class="modal fade" id="descricaoModal{{ unidade.id }}" tabindex="-1" role="dialog" aria-labelledby="descricaoModalLabel" aria-hidden="true">
                    <div class="modal-dialog" role="document">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title" id="descricaoModalLabel">Detalhes da Unidade</h5>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            <div class="modal-body">
                                {{ unidade.descricao }}
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-secondary" data-dismiss="modal">Fechar</button>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </tbody>
    </table>
     
</div>
    <button class="reservar-btn btn btn-primary">Fazer Reserva</button>
    <div id="reservar-popup" class="popup">
        <h2>Reservar Unidade</h2>
        <form method="post" action="{% url 'reservar_unidade' empreendimento.id %}" class="form-group">
            <div class="form-group">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn-primary">Efetuar Reserva</button>
            </div>
        </form>
    </div>

</div>
<br>
<br>
<br>
<footer class="footer mt-auto py-3">
    <div class="container">
        <span class="text-muted" style="display: block; text-align: center;">© 2023 Gabriel dos Reis Pereira. Todos os direitos reservados.</span>
    </div>
</footer>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
</body>
</html>

empreendimentos/templates/faq.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <link rel="icon" href="{% static 'img/iconapp.png' %}" type="image/png">

    <meta charset="UTF-8">
    <title>Dúvidas Frequentes</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
</head>
<body>
    <div class="container">
        <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm">
            <img class="my-0 mr-md-auto font-weight-normal" src="/static/media/logopreta.png" width="150px">
            <nav class="my-2 my-md-0 mr-md-3">
              <a class="p-2 text-dark" href="/lista_empreendimentos">Empreendimentos</a>
              <a class="p-2 text-dark" href="/faq/">FAQ</a>
              <a class="p-2 text-dark" href="https://api.whatsapp.com/send/?phone=55048988150135&text&type=phone_number&app_absent=0">Suporte</a>
            </nav>
            {% if user.is_authenticated %}
                <a class="btn btn-outline-primary" href="{% url 'logout' %}">Logout</a>
            {% endif %}
    
        </div>
        <br>
        <div class="starter-template text-center mx-auto">
            <h1>Perguntas Frequentes</h1>
            <p class="lead">Este FAQ foi elaborado para simplificar sua experiência, proporcionando insights valiosos sobre o uso eficiente do nosso sistema de gerenciamento de vendas. Encontre informações essenciais para otimizar seu trabalho e maximizar seus resultados.</p>
        </div>
        

        <br>
        <br>
        <div class="accordion" id="accordionExample">
            <div class="card">
            <div class="card-header" id="headingOne">
                <h5 class="mb-0">
                <button class="btn btn-link" type="button" data-toggle="collapse" data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                    Como faço para acessar o sistema?
                </button>
                </h5>
            </div>
        
            <div id="collapseOne" class="collapse show" aria-labelledby="headingOne" data-parent="#accordionExample">
                <div class="card-body">
                    O acesso ao nosso sistema é simples e direto. Basta utilizar suas credenciais de login fornecidas durante o processo de registro. Se você tiver problemas para acessar, nossa equipe de suporte está pronta para ajudar.                </div>
            </div>
            </div>
            <div class="card">
            <div class="card-header" id="headingTwo">
                <h5 class="mb-0">
                <button class="btn btn-link collapsed" type="button" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                    Quais são os requisitos mínimos para usar o sistema?
                </button>
                </h5>
            </div>
            <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionExample">
                <div class="card-body">
                    Nosso sistema é baseado em web e é compatível com a maioria dos navegadores modernos. Certifique-se de ter uma conexão estável com a internet para uma experiência otimizada.
            </div>
            </div>
            <div class="card">
            <div class="card-header" id="headingThree">
                <h5 class="mb-0">
                <button class="btn btn-link collapsed" type="button" data-toggle="collapse" data-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
                    Qual é a política de segurança adotada pelo sistema para proteger meus dados?
                </button>
                </h5>
            </div>
            <div id="collapseThree" class="collapse" aria-labelledby="headingThree" data-parent="#accordionExample">
                <div class="card-body">
                    A segurança dos seus dados é nossa prioridade. Implementamos medidas robustas de segurança, incluindo criptografia de ponta a ponta e procedimentos de autenticação avançados. Saiba mais sobre nossas práticas de segurança consultando nossa Política de Privacidade
                </div>
            </div>
            </div>
        </div>

        <br>
        <br>
        <br>
        <br>
        <footer class="footer mt-auto py-3">
            <div class="container">
                <span class="text-muted" style="display: block; text-align: center;">© 2023 Gabriel dos Reis Pereira. Todos os direitos reservados.</span>
            </div>
        </footer>
    </div>


    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
</body>
</html>

empreendimentos/templates/lista_empreendimentos.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <link rel="icon" href="{% static 'img/iconapp.png' %}" type="image/png">

    <meta charset="UTF-8">
    <title>Listade Empreendimentos</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
</head>
<body>
    {% if user.is_authenticated %}
    <div class="container">
        <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm">
            <img class="my-0 mr-md-auto font-weight-normal" src="/static/media/logopreta.png" width="150px">
            <nav class="my-2 my-md-0 mr-md-3">
              <a class="p-2 text-dark" href="/lista_empreendimentos">Empreendimentos</a>
              <a class="p-2 text-dark" href="/faq/">FAQ</a>
              <a class="p-2 text-dark" href="https://api.whatsapp.com/send/?phone=55048988150135&text&type=phone_number&app_absent=0">Suporte</a>
            </nav>
            {% if user.is_authenticated %}
                <a class="btn btn-outline-primary" href="{% url 'logout' %}">Logout</a>
            {% endif %}
    
        </div> 
    
      <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
        <h2 class="display-4">Explore Nossos Empreendimentos Exclusivos {{ user.username }}!</h2>
        <p class="lead">Descubra uma seleção única de empreendimentos e loteamentos projetados para superar suas expectativas. Cada propriedade é cuidadosamente escolhida para oferecer não apenas um lar, mas uma experiência de vida excepcional.</p>
      </div>
    
      <div class="container">
            <div class="card-deck">
                {% for empreendimento in empreendimentos %}
                    <div class="card">
                        {% if empreendimento.imagem %}
                            <img class="card-img-top" src="{{ empreendimento.imagem.url }}" alt="{{ empreendimento.nome }}" style="width: 100%; height: 300px; object-fit: cover;">
                        {% else %}
                            <p class="text-center">Sem imagem disponível</p>
                        {% endif %}
                        <div class="card-body">
                            <a href="{% url 'detalhes_empreendimento' empreendimento_id=empreendimento.id %}">
                                <h5 class="card-title">{{ empreendimento.nome }}</h5>
                            </a>
                            
                            <p class="card-text"><small class="text-muted">Tipo de Empreendimento: {{ empreendimento.get_tipo_empreendimento_display }}</small></p>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
    {% else %}
        <p>Você precisa estar logado para acessar esta página.</p>
    {% endif %}
    <br>
    <br>
    <br>
    <br>
    <footer class="footer mt-auto py-3">
        <div class="container">
            <span class="text-muted" style="display: block; text-align: center;">© 2023 Gabriel dos Reis Pereira. Todos os direitos reservados.</span>
        </div>
    </footer>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
</body>
</html>

empreendimentos/templates/logout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Logout</title>
</head>
<body>

    <h2>Logout</h2>

    <p>You have been logged out. <a href="{% url 'login' %}">Login again</a>.</p>

</body>
</html>